### PR TITLE
[ENH] Added breathe

### PR DESCRIPTION
**Pull request by stuwilkins**
Added the breathe package to convert doxygen documentation to sphinx (useful for areaDetector and c code in general)

### CODE REVIEW

**Comment by ericdill** [comment]
Can you note in the recipe that breathe is not python 3 compatible?  Other than that LGTM

**Comment by stuwilkins** [comment]
Ok where is the best place?


On Nov 29, 2015, at 1:51 PM, Eric Dill <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you note in the recipe that breathe is not python 3 compatible? Other than that LGTM

**Comment by ericdill** [comment]
You can put comments in a yaml file prefixed by a hash (`#`). Somewhere in the yaml file just note with a comment that breathe is not Python 3 compatible.

**Comment by ericdill** [comment]
I'm not sure where I got the idea that breathe 4.1.0 is not python 3 compatible.  It is tested on 3.3 and 3.4 on travis.  Thanks @stuwilkins

**Pull request merged**
