### PR TITLE
Add pims 0.3.2 and slicerator 0.9.4

### PR DESCRIPTION
**Pull request by danielballan**
New recipes for slicerator and pims

### CODE REVIEW

**Comment by danielballan** [comment]
Intentionally, these versions do not begin with 'v'. Trying to keep soft-matter clean from this issue.

**Comment by tacaswell** [comment]
Why git url for pims and pypi for slicerator?

**Comment by danielballan** [comment]
Related to the botched deployment on PyPI. :- (

**Comment by danielballan** [comment]
Superceded by #95

**Pull request closed without merging**
