### PR TITLE
databroker v0.3.0 recipe: 0.2.0 -> v0.2.0

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by danielballan** [comment]
Are we sure this is how this works? It's inconsistent and anecdotal evidence suggests that the v causes trouble.

**Comment by ericdill** [comment]
Yes. I'm quite sure.

With 'v' prefixing the versions of filestore and metadatastore in the meta.yaml
```
(nikea3) ✘-1 ~/dev/conda/conda-prescriptions/recipes/databroker/v0.3.0 [master ↑·1|…9]
12:26 $ cat meta.yaml
package:
  name: databroker
  version: v0.3.0

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: v0.3.0

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - pims
    - metadatastore >=v0.2.0
    - filestore >=v0.2.0
    - channelarchiver
    - six
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker
    - databroker.testing
    - databroker.examples
    - databroker.examples.sample_data
    - databroker.utils

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
```
and the build...
```
(nikea3) ✔ ~/dev/conda/conda-prescriptions/recipes/databroker/v0.3.0 [master ↑·1|…9]
12:26 $ conda build . --python=3.4
Removing old build environment
Removing old work directory
BUILD START: databroker-v0.3.0-py34_0
Fetching package metadata: ........
Solving package specifications: ............
The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1
    pip:        7.1.2-py34_0
    python:     3.4.3-0
    readline:   6.2-2
    setuptools: 18.3.2-py34_0
    sqlite:     3.8.4.1-1
    tk:         8.5.18-0
    wheel:      0.26.0-py34_1
    xz:         5.0.5-0
    zlib:       1.2.8-0

Linking packages ...
[      COMPLETE      ]|########################################################################| 100%
Removing old work directory
checkout: 'v0.3.0'
Cloning into '/Users/edill/mc/conda-bld/work'...
done.
Note: checking out 'v0.3.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at cf2a1fc... Tag v0.3.0
==> git log -n1 <==

commit cf2a1fc0bf6ff6697ddb878424d4e52be879c212
Author: Eric Dill <edill@bnl.gov>
Date:   Tue Sep 29 09:51:04 2015 -0400

    Tag v0.3.0


==> git describe --tags --dirty <==

v0.3.0


==> git status <==

HEAD detached at v0.3.0
nothing to commit, working directory clean


Package: databroker-v0.3.0-py34_0
source tree in: /Users/edill/mc/conda-bld/work
+ /Users/edill/mc/envs/_build/bin/python setup.py install
running install
running bdist_egg
running egg_info
creating databroker.egg-info
writing top-level names to databroker.egg-info/top_level.txt
writing databroker.egg-info/PKG-INFO
writing dependency_links to databroker.egg-info/dependency_links.txt
writing manifest file 'databroker.egg-info/SOURCES.txt'
reading manifest file 'databroker.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'databroker.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/databroker
copying databroker/__init__.py -> build/lib/databroker
copying databroker/_version.py -> build/lib/databroker
copying databroker/databroker.py -> build/lib/databroker
copying databroker/handler_registration.py -> build/lib/databroker
copying databroker/pims_readers.py -> build/lib/databroker
creating build/lib/databroker/testing
copying databroker/testing/__init__.py -> build/lib/databroker/testing
copying databroker/testing/decorators.py -> build/lib/databroker/testing
copying databroker/testing/noseclasses.py -> build/lib/databroker/testing
copying databroker/testing/utils.py -> build/lib/databroker/testing
creating build/lib/databroker/examples
copying databroker/examples/__init__.py -> build/lib/databroker/examples
copying databroker/examples/hdf_io.py -> build/lib/databroker/examples
creating build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/__init__.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/common_nonscalar.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/frame_generators.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/image_and_scalar.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/step_scan.py -> build/lib/databroker/examples/sample_data
creating build/lib/databroker/utils
copying databroker/utils/__init__.py -> build/lib/databroker/utils
copying databroker/utils/diagnostics.py -> build/lib/databroker/utils
UPDATING build/lib/databroker/_version.py
set build/lib/databroker/_version.py to '0.3.0'
creating build/bdist.macosx-10.5-x86_64
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/databroker
copying build/lib/databroker/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
copying build/lib/databroker/_version.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
copying build/lib/databroker/databroker.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
creating build/bdist.macosx-10.5-x86_64/egg/databroker/examples
copying build/lib/databroker/examples/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples
copying build/lib/databroker/examples/hdf_io.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples
creating build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/common_nonscalar.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/frame_generators.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/image_and_scalar.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/step_scan.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/handler_registration.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
copying build/lib/databroker/pims_readers.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
creating build/bdist.macosx-10.5-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/decorators.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/noseclasses.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/utils.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/testing
creating build/bdist.macosx-10.5-x86_64/egg/databroker/utils
copying build/lib/databroker/utils/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/utils
copying build/lib/databroker/utils/diagnostics.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/utils
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/_version.py to _version.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/databroker.py to databroker.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/hdf_io.py to hdf_io.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/common_nonscalar.py to common_nonscalar.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/frame_generators.py to frame_generators.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/image_and_scalar.py to image_and_scalar.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/step_scan.py to step_scan.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/handler_registration.py to handler_registration.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/pims_readers.py to pims_readers.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/testing/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/testing/decorators.py to decorators.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/testing/noseclasses.py to noseclasses.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/testing/utils.py to utils.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/utils/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/utils/diagnostics.py to diagnostics.cpython-34.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying databroker.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying databroker.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying databroker.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying databroker.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/databroker-0.3.0-py3.4.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing databroker-0.3.0-py3.4.egg
Copying databroker-0.3.0-py3.4.egg to /Users/edill/mc/envs/_build/lib/python3.4/site-packages
Adding databroker 0.3.0 to easy-install.pth file

Installed /Users/edill/mc/envs/_build/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg
Processing dependencies for databroker==0.3.0
Finished processing dependencies for databroker==0.3.0
found egg: /Users/edill/mc/envs/_build/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg
number of files: 2
Fixing permissions
Fixing permissions
BUILD END: databroker-v0.3.0-py34_0
TEST START: databroker-v0.3.0-py34_0
Fetching package metadata: ........
Solving package specifications: ............
Warning: 4 possible package resolutions (only showing differing packages):
	['metadatastore-v0.2.0.post49-49_gfe1fc63_py34.tar.bz2', 'pymongo-2.9-py34_0.tar.bz2'],
	['metadatastore-v0.2.0-py34_0.tar.bz2', 'pymongo-3.0.3-py34_0.tar.bz2'],
	['metadatastore-v0.2.0-nppy34_0.tar.bz2', 'pymongo-3.0.3-py34_0.tar.bz2'],
	['metadatastore-v0.2.0-np19py34_0.tar.bz2', 'pymongo-3.0.3-py34_0.tar.bz2'],

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    qt-4.8.7                   |                1        39.0 MB
    sip-4.16.9                 |           py34_0         210 KB
    six-1.10.0                 |           py34_0          17 KB
    pyqt-4.11.4                |           py34_0         4.0 MB
    databroker-v0.3.0          |           py34_0          39 KB
    ------------------------------------------------------------
                                           Total:        43.3 MB

The following NEW packages will be INSTALLED:

    boltons:                  15.0.0-py34_0
    channelarchiver:          0.0.4.post5-5_g365f325_npNonepy34
    databroker:               v0.3.0-py34_0
    decorator:                4.0.4-py34_0
    filestore:                v0.2.1.post0-0_gfdc4740_py34
    freetype:                 2.5.2-2
    h5py:                     2.5.0-np19py34_3
    hdf5:                     1.8.15.1-1
    humanize:                 0.5.1-py34_0
    jinja2:                   2.8-py34_0
    jpeg:                     8d-1
    jsonschema:               2.4.0-py34_0
    libpng:                   1.6.17-0
    libtiff:                  4.0.2-1
    markupsafe:               0.23-py34_0
    matplotlib:               1.4.3-np19py34_3
    metadatastore:            v0.2.0.post49-49_gfe1fc63_py34
    mongoengine:              0.8.7-py34_1
    networkx:                 1.10-py34_0
    nslsii_dev_configuration: 1-3
    numpy:                    1.9.3-py34_0
    openssl:                  1.0.1k-1
    pandas:                   0.16.2-np19py34_0
    pillow:                   3.0.0-py34_0
    pims:                     0.2.2-py34_0
    pip:                      7.1.2-py34_0
    prettytable:              0.7.2-py34_0
    pymongo:                  2.9-py34_0
    pyparsing:                2.0.3-py34_0
    pyqt:                     4.11.4-py34_0
    python:                   3.4.3-0
    python-dateutil:          2.4.2-py34_0
    pytz:                     2015.6-py34_0
    pyyaml:                   3.11-py34_1
    qt:                       4.8.7-1
    readline:                 6.2-2
    scikit-image:             0.11.3-np19py34_0
    scipy:                    0.16.0-np19py34_1
    setuptools:               18.3.2-py34_0
    sip:                      4.16.9-py34_0
    six:                      1.10.0-py34_0
    sqlite:                   3.8.4.1-1
    tifffile:                 0.3.1-np19py34_0
    tk:                       8.5.18-0
    tzlocal:                  1.1.2-py34_0
    wheel:                    0.26.0-py34_1
    xz:                       5.0.5-0
    yaml:                     0.1.6-0
    zlib:                     1.2.8-0

Fetching packages ...
qt-4.8.7-1.tar 100% |#####################################################| Time: 0:00:04   8.63 MB/s
sip-4.16.9-py3 100% |#####################################################| Time: 0:00:00   5.24 MB/s
six-1.10.0-py3 100% |#####################################################| Time: 0:00:00   1.43 MB/s
pyqt-4.11.4-py 100% |#####################################################| Time: 0:00:00   8.26 MB/s
databroker-v0. 100% |#####################################################| Time: 0:00:00  13.87 MB/s
Extracting packages ...
[      COMPLETE      ]|########################################################################| 100%
Linking packages ...
  1 package:
[      COMPLETE      ]|########################################################################| 100%
===== testing package: databroker-v0.3.0-py34_0 =====
import: 'databroker'
import: 'databroker.testing'
import: 'databroker.examples'
import: 'databroker.examples.sample_data'
import: 'databroker.utils'
===== databroker-v0.3.0-py34_0 OK =====
TEST END: databroker-v0.3.0-py34_0
Uploading to anaconda.org
Using binstar api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file ericdill/databroker/v0.3.0/osx-64/databroker-v0.3.0-py34_0.tar.bz2 ...
Distribution already exists. Please use the -i/--interactive or --force options or `anaconda remove ericdill/databroker/v0.3.0/osx-64/databroker-v0.3.0-py34_0.tar.bz2`
[Conflict] file osx-64/databroker-v0.3.0-py34_0.tar.bz2 already exists for package databroker version v0.3.0
```
upload failed because I've already built that package on my channel.

Now let me remove the 'v' from metadatastore/filestore
```
(nikea3) ✔ ~/dev/conda/conda-prescriptions/recipes/databroker/v0.3.0 [master ↑·1|…9]
12:26 $ vim meta.yaml
(nikea3) ✘-1 ~/dev/conda/conda-prescriptions/recipes/databroker/v0.3.0 [master ↑·1|✚ 1…9]
12:27 $ cat meta.yaml
package:
  name: databroker
  version: v0.3.0

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: v0.3.0

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - pims
    - metadatastore >=0.2.0
    - filestore >=0.2.0
    - channelarchiver
    - six
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker
    - databroker.testing
    - databroker.examples
    - databroker.examples.sample_data
    - databroker.utils

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
```

and build it again...

```
(nikea3) ✔ ~/dev/conda/conda-prescriptions/recipes/databroker/v0.3.0 [master ↑·1|✚ 1…9]
12:27 $ conda build . --python=3.4
Removing old build environment
Removing old work directory
BUILD START: databroker-v0.3.0-py34_0
Fetching package metadata: ........
Solving package specifications: ............
The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1
    pip:        7.1.2-py34_0
    python:     3.4.3-0
    readline:   6.2-2
    setuptools: 18.3.2-py34_0
    sqlite:     3.8.4.1-1
    tk:         8.5.18-0
    wheel:      0.26.0-py34_1
    xz:         5.0.5-0
    zlib:       1.2.8-0

Linking packages ...
[      COMPLETE      ]|########################################################################| 100%
Removing old work directory
checkout: 'v0.3.0'
Cloning into '/Users/edill/mc/conda-bld/work'...
done.
Note: checking out 'v0.3.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at cf2a1fc... Tag v0.3.0
==> git log -n1 <==

commit cf2a1fc0bf6ff6697ddb878424d4e52be879c212
Author: Eric Dill <edill@bnl.gov>
Date:   Tue Sep 29 09:51:04 2015 -0400

    Tag v0.3.0


==> git describe --tags --dirty <==

v0.3.0


==> git status <==

HEAD detached at v0.3.0
nothing to commit, working directory clean


Package: databroker-v0.3.0-py34_0
source tree in: /Users/edill/mc/conda-bld/work
+ /Users/edill/mc/envs/_build/bin/python setup.py install
running install
running bdist_egg
running egg_info
creating databroker.egg-info
writing top-level names to databroker.egg-info/top_level.txt
writing dependency_links to databroker.egg-info/dependency_links.txt
writing databroker.egg-info/PKG-INFO
writing manifest file 'databroker.egg-info/SOURCES.txt'
reading manifest file 'databroker.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'databroker.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/databroker
copying databroker/__init__.py -> build/lib/databroker
copying databroker/_version.py -> build/lib/databroker
copying databroker/databroker.py -> build/lib/databroker
copying databroker/handler_registration.py -> build/lib/databroker
copying databroker/pims_readers.py -> build/lib/databroker
creating build/lib/databroker/testing
copying databroker/testing/__init__.py -> build/lib/databroker/testing
copying databroker/testing/decorators.py -> build/lib/databroker/testing
copying databroker/testing/noseclasses.py -> build/lib/databroker/testing
copying databroker/testing/utils.py -> build/lib/databroker/testing
creating build/lib/databroker/examples
copying databroker/examples/__init__.py -> build/lib/databroker/examples
copying databroker/examples/hdf_io.py -> build/lib/databroker/examples
creating build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/__init__.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/common_nonscalar.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/frame_generators.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/image_and_scalar.py -> build/lib/databroker/examples/sample_data
copying databroker/examples/sample_data/step_scan.py -> build/lib/databroker/examples/sample_data
creating build/lib/databroker/utils
copying databroker/utils/__init__.py -> build/lib/databroker/utils
copying databroker/utils/diagnostics.py -> build/lib/databroker/utils
UPDATING build/lib/databroker/_version.py
set build/lib/databroker/_version.py to '0.3.0'
creating build/bdist.macosx-10.5-x86_64
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/databroker
copying build/lib/databroker/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
copying build/lib/databroker/_version.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
copying build/lib/databroker/databroker.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
creating build/bdist.macosx-10.5-x86_64/egg/databroker/examples
copying build/lib/databroker/examples/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples
copying build/lib/databroker/examples/hdf_io.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples
creating build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/common_nonscalar.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/frame_generators.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/image_and_scalar.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/examples/sample_data/step_scan.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data
copying build/lib/databroker/handler_registration.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
copying build/lib/databroker/pims_readers.py -> build/bdist.macosx-10.5-x86_64/egg/databroker
creating build/bdist.macosx-10.5-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/decorators.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/noseclasses.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/testing
copying build/lib/databroker/testing/utils.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/testing
creating build/bdist.macosx-10.5-x86_64/egg/databroker/utils
copying build/lib/databroker/utils/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/utils
copying build/lib/databroker/utils/diagnostics.py -> build/bdist.macosx-10.5-x86_64/egg/databroker/utils
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/_version.py to _version.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/databroker.py to databroker.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/hdf_io.py to hdf_io.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/common_nonscalar.py to common_nonscalar.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/frame_generators.py to frame_generators.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/image_and_scalar.py to image_and_scalar.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/examples/sample_data/step_scan.py to step_scan.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/handler_registration.py to handler_registration.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/pims_readers.py to pims_readers.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/testing/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/testing/decorators.py to decorators.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/testing/noseclasses.py to noseclasses.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/testing/utils.py to utils.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/utils/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/databroker/utils/diagnostics.py to diagnostics.cpython-34.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying databroker.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying databroker.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying databroker.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying databroker.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/databroker-0.3.0-py3.4.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing databroker-0.3.0-py3.4.egg
Copying databroker-0.3.0-py3.4.egg to /Users/edill/mc/envs/_build/lib/python3.4/site-packages
Adding databroker 0.3.0 to easy-install.pth file

Installed /Users/edill/mc/envs/_build/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg
Processing dependencies for databroker==0.3.0
Finished processing dependencies for databroker==0.3.0
found egg: /Users/edill/mc/envs/_build/lib/python3.4/site-packages/databroker-0.3.0-py3.4.egg
number of files: 2
Fixing permissions
Fixing permissions
BUILD END: databroker-v0.3.0-py34_0
TEST START: databroker-v0.3.0-py34_0
Fetching package metadata: ........
Solving package specifications:
Error: Could not find some dependencies for databroker v0.3.0 py34_0: filestore >=0.2.0
```

**Comment by danielballan** [comment]
Thanks for that SSCCE. :- P

This 'v' question has been bugging me for awhile... maybe we can look at the source to see how these versions are parsed.

**Comment by danielballan** [comment]
https://github.com/conda/conda/blob/b08d6e7166908922dd99c297d3f4fc751ab27a2a/conda/resolve.py#L30

**Comment by danielballan** [comment]
Conclusion, after reading the docstring linked above: We shouldn't have put 'v' in front of our version strings, but now that we have, breaking the pattern would be worse.

**Pull request merged**
