### PR TITLE
WIP!! Binstar magic

### PR DESCRIPTION
**Pull request by ericdill**
I've gotten most of the dependencies for our stack built via `binstar-build submit`. See https://conda.nsls2.bnl.gov/latest. 

It's getting there!

@danielballan or @stuwilkins I'm going to need some help getting some mac development stuff installed correctly. (#37)

Update 2015-04-15
===============
These packages are having problems:
- [ ] reindent (has syntax errors in py3)
- [ ] metadatastore cannot find the CONDA_ETC environmental variable
- [ ] filestore cannot find the CONDA_ETC environmental variable
- [ ] channelarchiver (master?) also, watch out for PyQt4 syntax errors on unix-64 with python3.4
- [ ] ophyd (requires metadatastore)
- [ ] epics-base (requires @tacaswell )
- [ ] reindent (has syntax errors in py3)
- [ ] pcaspy (requires epics-base)

### CODE REVIEW

**Comment by ericdill** [comment]
This is what has been built via `minstar-build submit` thus far...

```
130-199-219-139:releases ericdill$ binstar show latest
Using binstar api site https://conda.nsls2.bnl.gov/api
Username: latest
Member since: Tue Apr 14 15:23:49 2015
  +user_type: org
Packages:
     Name                      |  Version | Access       | Package Types   | Platforms      
     ------------------------- |   ------ | ------------ | --------------- | ---------------
     latest/carchivetools      |    1.9.0 | public       | conda           | linux-64, osx-64
                                          : None
     latest/certifi            | 14.05.14 | public       | conda           | linux-64, osx-64
                                          : None
     latest/channelarchiver    |          | public       | conda           | linux-64, osx-64
                                          : None
     latest/characteristic     |   14.3.0 | public       | conda           | linux-64, osx-64
                                          : None
     latest/conda_etc          |        1 | public       | conda           | linux-64, osx-64
                                          : None
     latest/dataportal         |          | public       | []              |                
                                          : None
     latest/epics-base         |          | public       | []              |                
                                          : None
     latest/lmfit              |    0.8.3 | public       | conda           | linux-64, osx-64
                                          : None
     latest/metadatastore      |          | public       | []              |                
                                          : None
     latest/mongoengine        |   v0.8.7 | public       | conda           | linux-64, osx-64
                                          : None
     latest/ncurses            |          | public       | conda           | linux-64       
                                          : None
     latest/nslsii_dev_configuration |        1 | public       | conda           | linux-64, osx-64
                                          : None
     latest/ophyd              |          | public       | []              |                
                                          : None
     latest/pcaspy             |          | public       | []              |                
                                          : None
     latest/protobuf           |    2.6.0 | public       | conda           | linux-64, osx-64
                                          : None
     latest/pyasn1-modules     |    0.0.5 | public       | conda           | linux-64, osx-64
                                          : None
     latest/pyspec             |    0.2.0 | public       | conda           | linux-64, osx-64
                                          : None
     latest/python             |    3.4.2 | public       | conda           | linux-64       
                                          : None
     latest/python3.4.2        |          | public       | []              |                
                                          : None
     latest/readline           |          | public       | []              |                
                                          : None
     latest/service_identity   |   14.0.0 | public       | conda           | linux-64, osx-64
                                          : None
     latest/tzlocal            |    1.1.2 | public       | conda           | linux-64, osx-64
                                          : None
```

**Comment by danielballan** [comment]
You are unstoppable.

**Comment by danielballan** [comment]
Let's resurrect this PR. Nightly builds would be great.

**Comment by ericdill** [comment]
not using binstar

**Pull request closed without merging**
