### PR TITLE
More recipies

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by ericdill** [comment]
I'll fix the merge conflicts locally and push this up to master

**Comment by ericdill** [comment]
I'll submit a patch that resolves the merge conflicts and with any updates

**Comment by tacaswell** [comment]
@ericdill Can this be closed and deleted?

**Comment by ericdill** [comment]
@tacaswell I am confident that I got everything, but I would appreciate you giving it a once-over

**Comment by tacaswell** [comment]
Eh, I trust you on this and it is probably less work to re-create one that got lost if we need it than to go over the changes with a fine tooth comb again.

**Comment by ericdill** [comment]
> I trust you on this 

:pray: :fingers-crossed: the trust is not misplaced...  that was a lot of recipes to merge together

>  probably less work to re-create one that got lost if we need it than to go over the changes with a fine tooth comb again

fair point

**Pull request closed without merging**
