### PR TITLE
Added libevent and tmux

### PR DESCRIPTION
**Pull request by stuwilkins**
Added tmux for if you want the latest and greatest ...

### CODE REVIEW

**Comment by klauer** [comment]
If having these in conda is working well for you, @stuwilkins, great, but personally I think this isn't a good place for such applications. 

Have you looked at [linuxbrew](https://github.com/Homebrew/linuxbrew) before? I've been very happy with it for my installs of the latest neovim, tmux, git, etc.

**Comment by stuwilkins** [comment]
Hi @klauer whatever you guys want to do is fine by me, but I needed to get over the incredibly old version installed with debian that we insist on using and this is becoming increasingly frustrating. If we are going to use 2 packaging systems such as conda for one and linuxbrew for system stye stuff that is fine by me, just let me know what you guys want to standardize on....

**Comment by stuwilkins** [comment]
@klauer Quick installation of *linuxbrew* worked OK here .. thanks!

**Comment by klauer** [comment]
Completely agree. It's awful working with such old versions.

I wasn't speaking for the group when talking about my preferences - I'm not sure what the standard is supposed to be (or if there is one). In any case, let me know how you make out with linuxbrew.

**Comment by stuwilkins** [comment]
Hi @klauer ! 

Thanks for bringing this to my attention, after playing it does seem to work quite well, certainly gets round the problem that we have with debian! 

As for the correct solution, I am not sure if the group have a direction I am happy to follow that but both seem to work quite well and get the same done. 

It just ["does exactly what is says on the tin"](https://en.wikipedia.org/wiki/Does_exactly_what_it_says_on_the_tin)

Fyi, I have started putting these guides up on the [beamline docs](http://nsls-ii-csx.github.io/guides/index.html) if anyone is interested.

**Comment by klauer** [comment]
Hi @stuwilkins, glad to hear it's working well for you. Nice work on getting some beamline docs/guides together!

**Pull request closed without merging**
