### PR TITLE
[ENH] Added build for git

### PR DESCRIPTION
**Pull request by stuwilkins**

### CODE REVIEW

**Comment by tacaswell** [comment]
Why?

**Comment by stuwilkins** [comment]
Because as we run Debian 0.1 the stock version is really old ....

Best wishes,
Stuart


On Aug 18, 2015, at 00:24, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:


Why?

**Comment by tacaswell** [comment]
Can you please add a `2.5.0` subfolder to put the files in?  This layout is to play nicely with some automated tools that we will be bringing on line 'soon'.

**Comment by tacaswell** [comment]
I added the folder and merged locally.

**Pull request merged**
