### PR TITLE
Epics base fix

### PR DESCRIPTION
**Pull request by stuwilkins**
Hi, here is an update to build epics base. Instead of copying, this now creates symlinks and uses the INSTALL_LOCATION set in CONFIG_SITE to properly install an epics base directory.

### CODE REVIEW

**Comment by tacaswell** [comment]
I am not sure symlinks will work as the files you are linking to in the build directory which will be blown away for the next thing you build.

**Comment by stuwilkins** [comment]
They do work as long as they are “intra” environment and relative (such as these are)

S
On Jan 28, 2015, at 11:17 AM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure symlinks will work as the files you are linking to in the build directory which will be blown away for the next thing you build.

**Comment by tacaswell** [comment]
Ah, I missed the `cd $PREFIX` and thought we were still sitting in the build directory.  :sheep:

**Comment by stuwilkins** [comment]
Btw: just pushed an update. I simplified the linking. If it looks good can you merge?

Thanks!
S
On Jan 28, 2015, at 3:25 PM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, I missed the cd $PREFIX and thought we were still sitting in the build directory. [:sheep:]

**Comment by tacaswell** [comment]
Trying to run this locally I get

```
../../../src/libCom/osi/os/default/epicsReadline.c:79:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
```

The header is in the build environment which makes me thing it is not looking in the right places for the headers.

**Comment by tacaswell** [comment]
I think you also need https://github.com/NSLS-II/conda-prescriptions/pull/5/files#diff-eb423eb8cb5a3a30a517d33aeccc966dR18 to be part of the diff.

**Comment by tacaswell** [comment]
See https://github.com/stuwilkins/conda-prescriptions/pull/1

**Comment by stuwilkins** [comment]
Hi Tom,

This push works. I checked that it builds on a fresh install of anaconda. The only caveat is that it needs the readline build from conda-prescriptions not the stock from anaconda. I don't think you need the patch you cited. 

S

**Comment by tacaswell** [comment]
Remove `readline-dev` from your system packages, it is picking up the wrong header for readline.h.

**Pull request merged**
