### PR TITLE
Pin bs v0.2.3 to python=3.4.3 at build time

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by tacaswell** [comment]
why?

**Comment by ericdill** [comment]
With `python >=3.4.3` in the build section of the meta.yaml the build fails because bluesky does not successfully import.

meta.yaml:
```
edill@xf23id1-srv1:~/dev/conda/conda-prescriptions/recipes/bluesky$ cat v0.2.3/meta.yaml
package:
  name: bluesky
  version: v0.2.3

source:
  git_url: https://github.com/NSLS-II/bluesky
  git_rev: v0.2.3

build:
  # Note that this will override the default build string with the Python
  # and NumPy versions
  number: 0

requirements:
  build:
    - python >=3.4.3

  run:
    - python >=3.4.3
    - jsonschema
    - super_state_machine
    - numpy
    - metadatastore
    - filestore
    - matplotlib
    - prettytable
    - cycler
    - traitlets
    - history
    - lmfit

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - 'bluesky'
    - 'bluesky.examples'

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD
```
build log for `conda build v0.2.3 --python=3.4`:
```
edill@xf23id1-srv1:~/dev/conda/conda-prescriptions/recipes/bluesky$ conda build v0.2.3/ --python=3.4
Removing old build directory
Removing old work directory
BUILD START: bluesky-v0.2.3-np19_0
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.15.0 but the
latest version is 1.17.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .
The following NEW packages will be INSTALLED:

    ncurses:    5.9-6
    openssl:    1.0.1k-1
    pip:        7.1.2-py35_0
    python:     3.5.0-0
    readline:   6.2.5-1
    setuptools: 18.1-py35_0
    sqlite:     3.8.4.1-1
    tk:         8.5.18-0
    wheel:      0.26.0-py35_0
    xz:         5.0.5-0
    zlib:       1.2.8-0

Linking packages ...
[      COMPLETE      ]|########################################################################| 100%
Removing old work directory
checkout: u'v0.2.3'
Cloning into '/home/edill/anaconda/conda-bld/work'...
done.
Note: checking out 'v0.2.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 170ee81... REL: v0.2.3
==> git log -n1 <==

commit 170ee81d959155c67f20f79985ddaefefcd06800
Author: danielballan <daniel.b.allan@gmail.com>
Date:   Tue Sep 29 07:10:57 2015 -0400

    REL: v0.2.3


==> git describe --tags --dirty <==

v0.2.3


==> git status <==

# Not currently on any branch.
nothing to commit (working directory clean)


Package: bluesky-v0.2.3-np19_0
source tree in: /home/edill/anaconda/conda-bld/work
+ /home/edill/anaconda/envs/_build/bin/python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/bluesky
copying bluesky/__init__.py -> build/lib/bluesky
copying bluesky/_version.py -> build/lib/bluesky
copying bluesky/broker_callbacks.py -> build/lib/bluesky
copying bluesky/broker_examples.py -> build/lib/bluesky
copying bluesky/callbacks.py -> build/lib/bluesky
copying bluesky/examples.py -> build/lib/bluesky
copying bluesky/global_state.py -> build/lib/bluesky
copying bluesky/hardware_checklist.py -> build/lib/bluesky
copying bluesky/qt_kicker.py -> build/lib/bluesky
copying bluesky/register_mds.py -> build/lib/bluesky
copying bluesky/run_engine.py -> build/lib/bluesky
copying bluesky/scans.py -> build/lib/bluesky
copying bluesky/scientific_callbacks.py -> build/lib/bluesky
copying bluesky/simple_scans.py -> build/lib/bluesky
copying bluesky/spec_api.py -> build/lib/bluesky
copying bluesky/standard_config.py -> build/lib/bluesky
copying bluesky/suspenders.py -> build/lib/bluesky
copying bluesky/utils.py -> build/lib/bluesky
creating build/lib/bluesky/tests
copying bluesky/tests/__init__.py -> build/lib/bluesky/tests
copying bluesky/tests/test_callbacks.py -> build/lib/bluesky/tests
copying bluesky/tests/test_documents.py -> build/lib/bluesky/tests
copying bluesky/tests/test_examples.py -> build/lib/bluesky/tests
copying bluesky/tests/test_hardware_checklist.py -> build/lib/bluesky/tests
copying bluesky/tests/test_logbook.py -> build/lib/bluesky/tests
copying bluesky/tests/test_scans.py -> build/lib/bluesky/tests
copying bluesky/tests/test_simple_api.py -> build/lib/bluesky/tests
copying bluesky/tests/test_snaking.py -> build/lib/bluesky/tests
copying bluesky/tests/test_suspenders.py -> build/lib/bluesky/tests
copying bluesky/tests/test_vertical_integration.py -> build/lib/bluesky/tests
copying bluesky/tests/utils.py -> build/lib/bluesky/tests
creating build/lib/bluesky/testing
copying bluesky/testing/__init__.py -> build/lib/bluesky/testing
copying bluesky/testing/decorators.py -> build/lib/bluesky/testing
copying bluesky/testing/noseclasses.py -> build/lib/bluesky/testing
creating build/lib/bluesky/schema
copying bluesky/schema/bulk_events.json -> build/lib/bluesky/schema
copying bluesky/schema/event.json -> build/lib/bluesky/schema
copying bluesky/schema/event_descriptor.json -> build/lib/bluesky/schema
copying bluesky/schema/run_start.json -> build/lib/bluesky/schema
copying bluesky/schema/run_stop.json -> build/lib/bluesky/schema
UPDATING build/lib/bluesky/_version.py
set build/lib/bluesky/_version.py to '0.2.3'
+ /home/edill/anaconda/envs/_build/bin/python setup.py install --single-version-externally-managed --record=/dev/null
running install
running build
running build_py
UPDATING build/lib/bluesky/_version.py
set build/lib/bluesky/_version.py to '0.2.3'
running install_lib
creating /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/__init__.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/broker_callbacks.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/broker_examples.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/callbacks.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/examples.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/global_state.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/hardware_checklist.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/qt_kicker.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/register_mds.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/run_engine.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/scans.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/scientific_callbacks.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/simple_scans.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/spec_api.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/standard_config.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/suspenders.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
copying build/lib/bluesky/utils.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
creating /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/__init__.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_callbacks.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_documents.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_examples.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_hardware_checklist.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_logbook.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_scans.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_simple_api.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_snaking.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_suspenders.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/test_vertical_integration.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
copying build/lib/bluesky/tests/utils.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests
creating /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/testing
copying build/lib/bluesky/testing/__init__.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/testing
copying build/lib/bluesky/testing/decorators.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/testing
copying build/lib/bluesky/testing/noseclasses.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/testing
creating /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/schema
copying build/lib/bluesky/schema/bulk_events.json -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/schema
copying build/lib/bluesky/schema/event.json -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/schema
copying build/lib/bluesky/schema/event_descriptor.json -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/schema
copying build/lib/bluesky/schema/run_start.json -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/schema
copying build/lib/bluesky/schema/run_stop.json -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/schema
copying build/lib/bluesky/_version.py -> /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/__init__.py to __init__.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/broker_callbacks.py to broker_callbacks.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/broker_examples.py to broker_examples.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/callbacks.py to callbacks.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/examples.py to examples.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/global_state.py to global_state.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/hardware_checklist.py to hardware_checklist.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/qt_kicker.py to qt_kicker.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/register_mds.py to register_mds.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/run_engine.py to run_engine.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/scans.py to scans.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/scientific_callbacks.py to scientific_callbacks.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/simple_scans.py to simple_scans.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/spec_api.py to spec_api.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/standard_config.py to standard_config.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/suspenders.py to suspenders.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/utils.py to utils.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/__init__.py to __init__.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_callbacks.py to test_callbacks.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_documents.py to test_documents.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_examples.py to test_examples.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_hardware_checklist.py to test_hardware_checklist.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_logbook.py to test_logbook.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_scans.py to test_scans.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_simple_api.py to test_simple_api.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_snaking.py to test_snaking.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_suspenders.py to test_suspenders.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/test_vertical_integration.py to test_vertical_integration.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/tests/utils.py to utils.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/testing/__init__.py to __init__.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/testing/decorators.py to decorators.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/testing/noseclasses.py to noseclasses.cpython-35.pyc
byte-compiling /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky/_version.py to _version.cpython-35.pyc
running install_egg_info
running egg_info
creating bluesky.egg-info
writing requirements to bluesky.egg-info/requires.txt
writing bluesky.egg-info/PKG-INFO
writing dependency_links to bluesky.egg-info/dependency_links.txt
writing top-level names to bluesky.egg-info/top_level.txt
writing manifest file 'bluesky.egg-info/SOURCES.txt'
reading manifest file 'bluesky.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'bluesky.egg-info/SOURCES.txt'
Copying bluesky.egg-info to /home/edill/anaconda/envs/_build/lib/python3.5/site-packages/bluesky-0.2.3-py3.5.egg-info
running install_scripts
writing list of installed files to '/dev/null'
number of files: 76
Fixing permissions
Fixing permissions
BUILD END: bluesky-v0.2.3-np19_0
TEST START: bluesky-v0.2.3-np19_0
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.15.0 but the
latest version is 1.17.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: ...............................
Warning: 2 possible package resolutions (only showing differing packages):
	[u'tifffile-0.3.1-nppy34_0.tar.bz2'],
	[u'tifffile-0.3.1-np19py34_0.tar.bz2'],

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bluesky-v0.2.3             |           np19_0         104 KB

The following NEW packages will be INSTALLED:

    bluesky:                  v0.2.3-np19_0
    boltons:                  15.0.0-py34_0
    certifi:                  14.05.14-py34_1
    cycler:                   0.9.0-py34_0
    decorator:                4.0.2-py34_0
    filestore:                v0.2.0-nppy34_0
    fontconfig:               2.11.1-4
    freetype:                 2.5.2-2
    h5py:                     2.5.0-np19py34_3
    hdf5:                     1.8.15.1-1
    history:                  v0.0.1.post39-39_g8e73e71_py34
    humanize:                 0.5.1-py34_0
    ipykernel:                4.0.3-py34_0
    ipython:                  4.0.0-py34_0
    ipython_genutils:         0.1.0-py34_0
    ipywidgets:               4.0.3-py34_0
    jinja2:                   2.8-py34_0
    jpeg:                     8d-0
    jsonschema:               2.4.0-py34_0
    jupyter_client:           4.0.0-py34_0
    jupyter_core:             4.0.6-py34_0
    libgfortran:              1.0-0
    libpng:                   1.6.17-0
    libsodium:                0.4.5-0
    libtiff:                  4.0.2-1
    libxml2:                  2.9.0-0
    lmfit:                    0.9.0rc2-np19py34_0
    markupsafe:               0.23-py34_0
    matplotlib:               1.5.0rc1-np19py34_0
    metadatastore:            v0.2.0-nppy34_0
    mistune:                  0.7.1-py34_0
    mongoengine:              0.8.7-py34_1
    nbconvert:                4.0.0-py34_0
    nbformat:                 4.0.0-py34_0
    ncurses:                  5.9-6
    notebook:                 4.0.4-py34_0
    nslsii_dev_configuration: 1-3
    numpy:                    1.9.2-py34_2
    openblas:                 0.2.14-3
    openssl:                  1.0.1k-1
    path.py:                  8.1.1-py34_0
    pexpect:                  3.3-py34_0
    pickleshare:              0.5-py34_0
    pillow:                   2.9.0-py34_0
    pims:                     v0.2.2.post138-138_gc98edfc_np19py34
    pip:                      7.1.2-py34_0
    prettytable:              0.7.2-py34_0
    ptyprocess:               0.4-py34_0
    pygments:                 2.0.2-py34_0
    pymongo:                  2.8-py34_0
    pyparsing:                2.0.3-py34_0
    pyqt:                     4.11.3-py34_1
    python:                   3.4.3-1
    python-dateutil:          2.4.2-py34_0
    pytz:                     2015.6-py34_0
    pyyaml:                   3.11-py34_1
    pyzmq:                    14.7.0-py34_0
    qt:                       4.8.6-3
    readline:                 6.2.5-1
    scipy:                    0.16.0-np19py34_1
    setuptools:               18.1-py34_0
    simplegeneric:            0.8.1-py34_0
    sip:                      4.16.5-py34_0
    six:                      1.9.0-py34_0
    sqlite:                   3.8.4.1-1
    super_state_machine:      1.0-py34_0
    system:                   5.8-2
    terminado:                0.5-py34_0
    tifffile:                 0.3.1-nppy34_0
    tk:                       8.5.18-0
    tornado:                  4.2.1-py34_0
    traitlets:                4.0.0-py34_0
    wheel:                    0.26.0-py34_0
    xz:                       5.0.5-0
    yaml:                     0.1.6-0
    zeromq:                   4.0.5-0
    zlib:                     1.2.8-0

Fetching packages ...
bluesky-v0.2.3 100% |#####################################################| Time: 0:00:00   3.21 MB/s
Extracting packages ...
[      COMPLETE      ]|########################################################################| 100%
Linking packages ...
[      COMPLETE      ]|########################################################################| 100%
===== testing package: bluesky-v0.2.3-np19_0 =====
import: u'bluesky'
Traceback (most recent call last):
  File "/home/edill/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import bluesky
ImportError: No module named 'bluesky'
TESTS FAILED: bluesky-v0.2.3-np19_0
```

**Comment by ericdill** [comment]
However, if I pin python ==3.4.3 in the meta.yaml then it builds correctly

**Comment by ericdill** [comment]
@danielballan can also confirm this

**Comment by ericdill** [comment]
Also of interest:

```
edill@xf23id1-srv1:~/dev/conda/conda-prescriptions/recipes/bluesky$ conda build v0.2.3/ --python=3.4.3
Error: CONDA_PY must be major.minor, like 3.4, not 343
```

**Comment by tacaswell** [comment]
wee, more weirdness in dependency resolution!

**Pull request merged**
