### PR TITLE
Add eiger-io recipe

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by ericdill** [comment]
You do not need to out quotes around. `- 'eiger_io.fs_handler'`. This is not a blocking issue, just a heads up.

What is the generated file name for v0.0.3? I am in the car and cannot check this myself

**Comment by danielballan** [comment]
The file name of the conda package? Why do you ask?

**Comment by ericdill** [comment]
Yes. I want to make sure that the python version is embedded in the file name.  Many of our conda recipes have specific build strings (e.g.) [https://github.com/NSLS-II/conda-prescriptions/blob/master/recipes/channelarchiver/v0.0.5.post6%2Bgfac126f/meta.yaml#L11] that force the python version to be in the file name.

**Comment by ericdill** [comment]
Ok, the answer to my question is that the python version is not embedded in the file name, so it is not possible to have multiple versions of this library.  But that is not even possible because the build is pinned to python 3.4.3!  Why is the build pinned to 3.4.3? eiger-io is not compatible with python 3.5?

**Comment by danielballan** [comment]
Actually no, I probably copy/pasted the bluesky recipe. Will fix. Remind
me, why is the bluesky recipe is pinned?

**Comment by ericdill** [comment]
It was a sloppy fix.  It was the fastest way I could get the bluesky conda package building.  For whatever reason, `import bluesky` was failing if the meta.yaml looked like this:
```
build:
  - python >=3.4.3
```

but it was succeeding if the meta.yaml was:
```
build:
  - python == 3.4.3
```

(Clearly) this should be ironed out, but I have not had the time to circle back to it yet.

**Comment by danielballan** [comment]
Fair. I'll try to take a look. I would have done the same -- progress can't
wait for every little idiosyncrasy of conda.

**Comment by ericdill** [comment]
For this PR, I would suggest simply removing all pinning of python versions from these recipes.  It should be good to go after that

**Comment by ericdill** [comment]
Awesome, thanks!

**Pull request merged**
